version: "3.7"

services:
  redis:
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
  db:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  web:
    build:
      context: ./hospital
      dockerfile: Dockerfile.prod
      args:
        HOME: /home/app
        APP_HOME: /home/app/web
        STATIC_FILES: /home/app/web/staticfiles
        MEDIA_FILES: /home/app/web/mediafiles
    volumes:
      - static:/home/app/web/static
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    depends_on:
      - db
    expose:
      - 8000
    env_file:
      - ./.env.prod
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - web
    ports:
      - "3333:80"
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles

volumes:
  postgres_data:
  static:
  static_volume:
  media_volume:
